#!/usr/bin/env bash

icon="$HOME/.config/pics/lock.png"
tmpbg='/tmp/screen.png'

(( $# )) && { icon=$1; }

scrot "$tmpbg"
convert "$tmpbg" -scale 10% -scale 1000% "$tmpbg"
convert "$tmpbg" "$icon" -gravity center -composite -matte "$tmpbg"
# steam messes with dpms force off.
killall steam && i3lock -u -i "$tmpbg" & sleep 5 && xset dpms force off
