#!/usr/bin/env bash

sudo add-apt-repository ppa:kgilmer/speed-ricer
sudo apt-get update

sudo apt-get install -y i3-gaps-wm \
	arc-theme \
	fish \
	flameshot \
	feh \
	fonts-firacode \
	fzy \
	git \
	picom \
	i3blocks \
	i3lock \
	i3status \
	moka-icon-theme \
	nnn \
	pulseaudio \
	python \
	python-pip \
	python3 \
	python3-pip \
	rofi \
	screenfetch \
	terminator \
	pass \
	stow \
	fortune \
	cowsay \
	lolcat \
	vifm \
	libiw-dev \
	libnl-genl-3-dev \
	libpulse-dev \
	libxcb-xkb-dev \
	libxcb-xrm-dev \
	libxcb-cursor-dev \
	cmake \
	cmake-data \
	pkg-config \
	python3-sphinx \
	libcairo2-dev \
	libxcb1-dev \
	libxcb-util0-dev \
	libxcb-randr0-dev \
	libxcb-composite0-dev \
	python-xcbgen \
	xcb-proto \
	libxcb-image0-dev \
	libxcb-ewmh-dev \
	libxcb-icccm4-dev \
	libjsoncpp-dev \
	libcurl4-openssl-dev \
	oomox


#spotify-tui
sudo snap install spt

sudo snap install --edge nvim --classic

#Get my password-store passwords (mostly for spotifyd)
git clone git@github.com:StewartThomson/pass-store.git $XDG_DATA_HOME/pass

chsh -s `which fish`

sudo cp i3.desktop /usr/share/xsessions

sudo update-alternatives --install /usr/bin/x-session-manager x-session-manager /usr/bin/i3 60

