#!/usr/bin/env bash

sudo apt-get update

sudo apt-get install -y \
	arc-theme \
	fish \
	flameshot \
	feh \
	fonts-firacode \
	fzy \
	git \
	picom \
	i3blocks \
	i3lock \
	i3status \
	moka-icon-theme \
	nnn \
	pulseaudio \
	python \
	python-pip \
	python3 \
	python3-pip \
	rofi \
	screenfetch \
	terminator \
	pass \
	stow \
	fortune \
	cowsay \
	lolcat \
	vifm \
	libiw-dev \
	libnl-genl-3-dev \
	libpulse-dev \
	libxcb-xkb-dev \
	libxcb-xrm-dev \
	libxcb-cursor-dev \
	cmake \
	cmake-data \
	pkg-config \
	python3-sphinx \
	libcairo2-dev \
	libxcb1-dev \
	libxcb-util0-dev \
	libxcb-randr0-dev \
	libxcb-composite0-dev \
	python-xcbgen \
	xcb-proto \
	libxcb-image0-dev \
	libxcb-ewmh-dev \
	libxcb-icccm4-dev \
	libjsoncpp-dev \
	libcurl4-openssl-dev \
	oomox \
	neovim \
	libxcb1-dev libxcb-keysyms1-dev libpango1.0-dev libxcb-util0-dev libxcb-icccm4-dev libyajl-dev libstartup-notification0-dev libxcb-randr0-dev libev-dev libxcb-cursor-dev libxcb-xinerama0-dev libxcb-xkb-dev libxkbcommon-dev libxkbcommon-x11-dev autoconf libxcb-xrm0 libxcb-xrm-dev automake libxcb-shape0-dev libxcb-xrm-dev

# Install i3 gaps
# clone the repository
git clone https://www.github.com/Airblader/i3 i3-gaps
cd i3-gaps

# compile & install
autoreconf --force --install
rm -rf build/
mkdir -p build && cd build/

# Disabling sanitizers is important for release versions!
# The prefix and sysconfdir are, obviously, dependent on the distribution.
../configure --prefix=/usr/local --sysconfdir=/etc --disable-sanitizers
make -j2
sudo make install

#Get my password-store passwords (mostly for spotifyd)
git clone git@github.com:StewartThomson/pass-store.git $XDG_DATA_HOME/pass

chsh -s `which fish`

sudo cp i3.desktop /usr/share/xsessions

sudo update-alternatives --install /usr/bin/x-session-manager x-session-manager /usr/bin/i3 60

